### ISSUE TITLE
Switch dynamodb to on-demand provisioning

### ISSUE THREAD

**Issue by rlister** [ArcadiaPower/goldfinch#19]
https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-amazon-dynamodb-on-demand/

> When enabling DynamoDB On-Demand using CloudFormation don't forget to remove the provisioned capacity settings, otherwise the update will succeed, but don't change to on-demand. See also https://awsdevelopers.slack.com/archives/CAYLHJPGU/p1543480562641900

**Comment by rlister** [comment]
```
DynamoDbResource:
    Type: AWS::DynamoDB::Table
    Properties: 
        BillingMode: PAY_PER_REQUEST
        # Other properties
```
